IllusionMods/HSPlugins

UsefulStuff.Core/Features/CameraShortcuts.cs
It turns out, in AI and HS2, `BaseCameraControl_Ver2` and `BaseCameraControl` already has the 10x delta compensation applied so the camera is too fast in character creator when moving with the keyboard.
This fixes it. I tried to make a little change to the code I could.
=> [AI/HS2] [US] Fix unnecessary delta time compensation

ToolBox/HarmonyExtensions.cs, VideoExport.AI/VideoExport.AI.csproj, VideoExport.AI/packages.config, VideoExport.Core/ScreenshotPlugins/ScreencapPlugin.cs, VideoExport.Core/VideoExport.Core.projitems, VideoExport.Core/VideoExport.cs, VideoExport.HS2/VideoExport.HS2.csproj, VideoExport.HS2/packages.config, VideoExport.KK/VideoExport.KK.csproj, VideoExport.KK/packages.config, VideoExport.KKS/VideoExport.KKS.csproj, VideoExport.KKS/packages.config
=> [VE] Fix Screencap mode not working in KKS

Timeline.Core/BuiltInInterpolables.cs, Timeline.Core/Timeline.cs, Timeline.KK/Timeline.KK.csproj, Timeline.KK/packages.config, Timeline.KKS/Timeline.KKS.csproj, Timeline.KKS/packages.config
=> [TL] Fix compatibility with animation sideloader zipmod

Core.PoseEditor/AMModules/BlendShapesEditor.cs
=> [PE] Fix BlendShapesEditor modifications to face to be lost for custom heads when loading presets

Core.PoseEditor/AMModules/BlendShapesEditor.cs
Fix by 갈대 at https://arca.live/b/honeyselect/88832843?p=1
=> [PE] Fix losing head blend shape edits if chara uses different head

Core.PoseEditor/AMModules/AdvancedModeModule.cs, Core.PoseEditor/AMModules/BonesEditor.cs, Core.PoseEditor/PoseController.cs
- Add 0 buttons
- Add list filtering toggle to show only modified bones
- Add world position toggle to switch edit controls to world space
- Limit the rate of value change when holding left mouse on a button
- Improve auto scrolling list to selected bone
Based on changes from a modified KKPE.dll I was sent, no idea who the author is.
=> [PE] Bone editor upgrades

Core.PoseEditor/BoneReorganizer.cs, Core.PoseEditor/Core.PoseEditor.projitems, Core.PoseEditor/HSPE.cs, Core.PoseEditor/MainWindow.cs
=> [PE] BoneReorganizer: reorganize FK bones in order of transform tree

Core.PoseEditor/AMModules/DynamicBonesEditor.cs, Core.PoseEditor/HSPE.cs
But its less mad and less evil
=> [PE] Add option to only show the current gizmo

NodesConstraints.Core/NodesConstraints.cs
Shown damp values were not updated when selecting a new contraint
=> [NC] Fix damp values not updated when selecting a new contraint

NodesConstraints.Core/NodesConstraints.cs
Fixes https://github.com/IllusionMods/HSPlugins/issues/71
=> [NC] Fix scaling constraints looking at the original X scale only for all axis

Timeline.Core/Timeline.cs
To improve the listability of the timeline, a function to adjust the height of the rows has been implemented.
Adjustment can be made by scrolling over the logo.
I couldn't think of an appropriate operation, so I did this for now.
~~And by the way, I didn't know you could adjust the transparency by scrolling while holding down the Ctrl.~~
https://github.com/IllusionMods/HSPlugins/assets/32182799/101cc121-9f45-4aae-8c65-3a367bfd4f2a
=> [TL]Interpolable height adjustment

Timeline.Core/Timeline.cs
Some functions have been added to the timeline interface.
If it looks OK, please merge it.
This PR was created by commission from Noctis17.
- Enhancement of behavior when clicking on the guide while holding down the left Alt key  
The Timeline now responds when you click on the displayed guides (GuideMove, GuideRotation, GuideScale).  
In addition, interpolation is selected according to the studio's guide object selection mode (position, rotation, scale).  
It now scrolls to the selected object.    
- Enhanced filter for searching interpolation
The following functions have been added to interpolation.
1) OR search using "|"
2) AND search using "&" and ","
3) Wildcard ("?"."*")
If you enter "pos,leg", etc., only the foot positions will be displayed in the window.
In addition, after …
=> Enhanced Timeline interface

Core.PoseEditor/CharaPoseController.cs
Fix the problem I mentioned in Discord.
=> [PE] Fix the anus not following the crotch correction in KK/KKS

Core.PoseEditor/AMModules/AdvancedModeModule.cs, Core.PoseEditor/AMModules/BlendShapesEditor.cs, Core.PoseEditor/AMModules/ClothesTransformEditor.cs, Core.PoseEditor/Core.PoseEditor.projitems, Core.PoseEditor/PoseController.cs
BlendshapeEditor : new function - adjust blendshape data that  non matched between origin character, current character
ClothesTransformEditor : new module - Change Transform of 'clothes skinnedmeshRenderer's bone' to new Transform (Only HS2)
=> [PE] [AI/HS2]Add ClothesTransformEditor module; [ALL]BlendshapeEditor improvement

Core.PoseEditor/AMModules/AdvancedModeModule.cs, Core.PoseEditor/AMModules/ClothesTransformEditor.cs
AdvancedModemodule - Fix to avoid errors when building games that do not use ClothesTransformEditor
ClothesTransformEditor - Changed how to find 'Body Transform' from keyword seaching to Body Renderer's bones
=> [PE] ClothesTransformEditor - Changed how to find 'Body Transform'

Core.PoseEditor/AMModules/AdvancedModeModule.cs, Core.PoseEditor/AMModules/ClothesTransformEditor.cs
ClothesTransformEditor - Add Refresh Clothes Renderer button used when 'Renderer' changes due to unrecognizable external factors
=> [PE] ClothesTransformEditor - Add Refresh Clothes Renderer button

Timeline.Core/Timeline.cs, ToolBox/TimelineCompatibility.cs, VideoExport.Core/VideoExport.cs
Added a function that estimates the real time duration of the timeline as timescale changes and used it in Video Export.
https://github.com/user-attachments/assets/8118148d-fadb-4a6f-992b-b17fe01c754a
=> [TL][VE] Estimate real time duration for VE

Core.PoseEditor/MainWindow.cs
Mentioning #95, should do the job. Thankfully track is kept of who becomes what.
=> [PE] Fix imports losing data caused by #95

Core.PoseEditor/AMModules/AdvancedModeModule.cs, Core.PoseEditor/AMModules/BlendShapesEditor.cs, Core.PoseEditor/AMModules/ClothesTransformEditor.cs, Core.PoseEditor/MainWindow.cs
BlendshapeEditor- bug fix - eyecomponent link
ClothesTransformEditor - only char has CTE
=> [PE] BlendshapeEditor- eyecomponent link bug fix and linkKey Caching, preset mixmode prototype

VideoExport.Core/Extensions/AFFMPEGBasedExtension.cs, VideoExport.Core/Extensions/AVIFExtension.cs, VideoExport.Core/Extensions/GIFExtension.cs, VideoExport.Core/Extensions/IExtension.cs, VideoExport.Core/Extensions/MOVExtension.cs, VideoExport.Core/Extensions/MP4Extension.cs, VideoExport.Core/Extensions/WEBMExtension.cs, VideoExport.Core/Extensions/WEBPExtension.cs, VideoExport.Core/Resources/English.xml, VideoExport.Core/Resources/中文.xml, VideoExport.Core/VideoExport.Core.projitems, VideoExport.Core/VideoExport.cs
This PR adds the WEBP and AVIF extensions.
Also fixes an issue introduced by the UI update because `IExtension.GetArguments` resets the progress as a side effect. Moved the reset into a separate function.
Closes https://github.com/IllusionMods/HSPlugins/issues/143.
=> [VE] WEBP and AVIF extensions

VideoExport.AI/VideoExport.AI.csproj, VideoExport.AI/packages.config, VideoExport.Core/ScreenshotPlugins/ScreencapPlugin.cs, VideoExport.Core/VideoExport.cs, VideoExport.HS2/VideoExport.HS2.csproj, VideoExport.HS2/packages.config, VideoExport.KK/VideoExport.KK.csproj, VideoExport.KK/packages.config, VideoExport.KKS/VideoExport.KKS.csproj, VideoExport.KKS/packages.config
Need to wait for https://github.com/IllusionMods/BepisPlugins/pull/221 to be merged and released (for the updated nuget packages). Otherwise already functions correctly if references are manually replaced to new screencap dll.
=> [VE] Support new ScreenshotManager (v21+)
