UsefulStuff.Core/Features/AutoJointCorrection.cs
UsefulStuff.Core/HSUS.cs

I think It may be a good time to correct the translation of the joint correction menu.
関節補正=Joint Adjustment -> Joint Correction
Forearm - > Arm, Foot -> Leg, Forearm Group - > Forearm

[US] Improve AutoJoinCorrection feature to be individually configurable

---

Core.PoseEditor/AMModules/BonesEditor.cs

wildcard support: translate "\*" and "?" to regex (".\*" and ".") in the background for search.
The search happened every frame at first, which could cause slowdowns (and was only made worse by the added regex). Now the search itself is only performed when the filter is updated

[PoseEditor] Add wildcard support to search and improve search performance

---

Core.PoseEditor/AMModules/BlendShapesEditor.cs
Core.PoseEditor/Extensions.cs

Fixed a bug in Sunshine Studio that caused a Same key exception in BlendShapesEditor.Init when changing characters.
Reproduction procedure:
1. launch KKS studio
2. load any character
3. change character
```
ArgumentException: An item with the same key has already been added. Key: ct_head (FaceBlendShape)
at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <fb001e01371b4adca20013e0ac763896>:0 
at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
at HSPE.AMModules.BlendShapesEditor.Init () [0x00022] in <4777fff9a68141d0817e44d0eec04cdb>:0 
at HSPE.AMModules.BlendShapesEditor.<OnCharacterReplaced>b__49_0 …
```

[PE][KKS] Fix same key exception

---

Core.PoseEditor/AMModules/BlendShapesEditor.cs

Fixed a bug that caused blendshapes to be reset when duplicating a character
Reproduction procedure:
1. Launch Studio
2. Add any character
3. Edit the character's blendshape
4. Select a character from the workspace and press Ctrl+D to duplicate
5. The original character's blendshape will be reset
This is due to the fact that the original blendshape was Clear()ed in LoadFrom. However, even if you return at the beginning of LoadFrom(), the blendshape will still be copied. It seems that somewhere else the blendshape is being duplicated by some other code.
But I thought it was not intended that LoadFrom not do the copying, so I fixed it for good.
As a side note, Clone() was not needed. It appears that the instances are not shared. Editing blendshapes is independent. However, the code before …

[PE] Fixed a bug that caused blendshapes to be reset when duplicating a character

---

Core.PoseEditor/AMModules/BlendShapesEditor.cs
Core.PoseEditor/AMModules/DynamicBonesEditor.cs
Core.PoseEditor/AMModules/IKEditor.cs
Core.PoseEditor/PoseController.cs

Fixed #58 and related code.
Please merge if it looks OK.
Added workaround for cases with deleted objects in _childObjects.
Code for copying _childObjects in LoadFrom() has been replaced with code that registers itself with the parent object when the object is copied. Using Find() causes a problem where a second child with the same name cannot be found if it exists. This problem can be avoided by spontaneously registering the child.
OnParentage is divided into two parts.
In the individual objects, we are only deleting from the _childObjects of the old parent object.
The newly added function OnParentageRoot() adds children to the _childObjects of the new parent.
It may not check all cases, but it should be more stable. Maybe. 
Of the three commits, let me know if the back two are in danger. …

[PE] Fix Null Reference Exception and more

---

VideoExport.Core/Resources/English.xml
VideoExport.Core/Resources/中文.xml
VideoExport.Core/VideoExport.cs

Added option to set export FPS. Please merge if it looks OK.
The combination of IK, NodesConstraints and animations can result in unnatural motion when outputting video at low FPS.
The following video has a hand pinned to another character's chest with NodeConstraints. Can you see how the hands sometimes slide unnaturally at low FPS (2) and (3)?
Avoid this by capturing at high FPS and exporting at low FPS.
To be correct, slides do occur at high FPS, but they are not noticeable because of their small volume.
Apparently some things don't work well when deltaTime is large.
① 15FPS from 60FPS:
https://github.com/IllusionMods/HSPlugins/assets/4230203/40ff4091-c44b-4cba-b3ae-e8bfe4f1811e
② 15FPS:
https://github.com/IllusionMods/HSPlugins/assets/4230203/b7a9f0cd-e3a3-4337-858c-f72fd4a779f6
③ …

[VE] Added option to set export FPS

---

NodesConstraints.Core/NodesConstraints.cs

**Change factors**
Multiply the movement/rotation/scale change of the parent by a factor and apply that movement to the child. Defaults to 1 to keep current behaviour.
e.g. with a movement factor of 2 on the position, the following would occur:
parent: (0, 0, 0) -> (3, 6, 0)
child: (0, 0, 0) -> (6, 12, 0)
**Movement dampening**
Dampens the childs movement towards the parent, making it follow the parent instead of a 1:1 position lock.
0 (or smaller) disables this and keeps current behaviour (and is the default).
The higher the number, the faster the child will follow the parent.
**Axis locking**
Only constrain the chosen axis to the parent. Letting the child move freely on the non-constrained axis.
The X/Y/Z labels are replaced by toggles styled as buttons, and are all turned on by default …

[NC] Add contraint change factors, movement dampening and variable axis locking

---

NodesConstraints.Core/NodesConstraints.cs

NC resets the child back to its original position when the constraint is disabled/removed. Got told this was actually something problematic for animators, and they have to use some weird constraint setup to go around this behaviour.
This toggle just allows you to disable the resetting on a per contraint basis. 
Also fixed the copying of contraints, since I seem to have forgotten in all previous PR's

[NC] Add toggle for children resetting to original transform when contraint is disabled/removed

---

NodesConstraints.Core/NodesConstraints.cs

Prior to ver1.3, a constraint was working to prevent the parent lossyScale from being affected, so we modified it to behave similarly.
Also, when the constraints were disabled, only Scale was not being temporarily reset, so this was added.
There were times when the constraints of scenes created before ver 1.3 were broken, but I believe this fix will eliminate such events.

[NC] Modified scale formulas to work like prior to v1.3

---

NodesConstraints.Core/NodesConstraints.cs

NodesConstraints GUI was large and took up a lot of screen real estate.
So, it may be a trivial change, but we have made it possible to set the scroll list height from Config.
Conversely, the height can be increased to display more items.
If the settings are left as default, you can rest assured that nothing will change.

[NC] Height of the Constraints list and the Nodes list can be set from Config

---

Timeline.Core/Timeline.cs

Added the ability to extend the timeline selection up and down by dragging while holding down the left Alt key.
Please merge if there is no problem.
As a matter of fact, I am unfamiliar with the timeline. Sorry if there is already some alternative function.
Normal drag:
Drag + LeftAlt:
Expands the vertical selection to the maximum.
This PR was developed from a commission by Noctis17.

[TL] Select the entire column when holding Left Alt

---

NodesConstraints.Core/NodesConstraints.cs

The debug lines would stay on screen if you closed the the NC window through the "X" button. This would not happen when using the shortcut again to close the window

[NC] Disable the debugline when closing window through the close button

---

Core.PoseEditor/AMModules/BonesEditor.cs

Only when you press and hold the XYZ button on Scale, there was no initial pooling, so I added it.

[PE]Fixed behavior when holding XYZ scale button

---

Core.PoseEditor/AMModules/CollidersEditor.cs

As the title says.
This was an annoying behavior, so I'm removing the part that caused it.
Please merge if there is no problem!

[PE] Fix Collider height being changed on its own just by selecting an item.

---

Core.PoseEditor/HSPE.cs
Core.PoseEditor/MainWindow.cs
Core.PoseEditor/PoseController.cs

Advanced mode is disabled by default on all items, and is disabled using `this.ExecuteDelayed2(() => { enabled = other.enabled; }, 2);`  in the `Awake` function.
This just syncs the controller enabled state with the source controller when it's copied

[PE] Keep advanced mode enabled on object copy

---

Timeline.Core/Timeline.cs

Fixed a bug where all new keyframes shared the same **AnimationCurve** as the last keyframe of the **interpolable**.
This bug was the one mentioned by **YuukiS** in the discord server.

[TL] Fixed keyframes sharing the same AnimationCurve.

---

VideoExport.Core/ScreenshotPlugins/Bitmap.cs

The black pixels in the current frame may become transparent due to the alpha channel of 0, possibly caused by NaN values in calculations, which can lead to exposure of the previous frame in the current one. Therefore, we always begin by clearing the graphics black.

[VE] Fix the issue where some pixels of the previous frame are exposed when exporting video in Win32 mode

---

Core.PoseEditor/AMModules/BlendShapesEditor.cs
Core.PoseEditor/AMModules/BoobsEditor.cs
Core.PoseEditor/AMModules/CollidersEditor.cs
Core.PoseEditor/AMModules/DynamicBonesEditor.cs
Core.PoseEditor/MainWindow.cs

- Added a toggle in the **Colliders window** that controls whether newly registered DynamicBones should start enabled or disabled. 
- Added 'All on' and 'All of' buttons for each individual object in the **Colliders window**.
- Added a search bar in the **Colliders window**.
- Added a 'Link BlendShapes with same name' toggle option in the **BlendShapes window** and its Timeline Interpolable.
This closes #18 and closes #85 
https://github.com/user-attachments/assets/968e5662-3f3d-43d8-aff9-4d3b8fd2b71b
https://github.com/user-attachments/assets/cf819553-9b81-4c9f-a151-25cd8f930931

[PE] Collider and BlendShapes modules enhancements.

---

Core.PoseEditor/AMModules/BlendShapesEditor.cs

The conditions for updating _blendIndics were not appropriate, resulting in a terrible waste of memory.
I don't have the full specs of the revamped PE, but this is probably the way it was originally intended to work.

[PE]BlendshapeEditor - Fix memory waste

---

Core.PoseEditor/AMModules/BlendShapesEditor.cs

All Blendshapes are reset when the reset button in the lower right corner is pressed.
Fixed so that only the currently selected BlendRenderer is reset.

[PE]BlendshapeEditor - Fix reset button resetting all blendshape

---

NodesConstraints.Core/NodesConstraints.cs

Allows you to set the main camera as the parent in a constraint. By having nothing selected the parent button will target the main camera transform.
Mostly useful to make something like a D-modlight always point the same way the camera is looking, or to let an item always face the camera.
This also keeps working when switching to camera objects.
Internally I used -2 as the parent index to indicate it should use the camera instead for saving and loading (-1 is left as the default for when there is no index).
It doesn't have a _ton_ of use, especially since items can get kind of jittery when bound to the camera. But stuff like linking the D-Modmap don't really have a visible jitter

[NC] Allow main camera as parent

---

Timeline.Core/Timeline.cs

When doing UseCurrentTime or DragAtCurrentTime, keyframes could not be moved to the last time.
I don't think there is any particular advantage to looping within _duration.

[TL]Fix CurrentTime calculation

---

Core.PoseEditor/AMModules/BoobsEditor.cs
Core.PoseEditor/AMModules/CollidersEditor.cs
Core.PoseEditor/AMModules/DynamicBonesEditor.cs
Core.PoseEditor/MainWindow.cs
Core.PoseEditor/PoseController.cs

- Fixed problem where some colliders with the new option didn't load properly.
- Fixed an old bug where colliders couldn't be imported/duplicated properly.
- Added an identifier for load sessions so objects can keep track of each other between load types (Load/Import/External).
This closes #117

[PE] Colliders Editor module fixes and code improvements.

---

VideoExport.Core/Extensions/IExtension.cs
VideoExport.Core/Extensions/MOVExtension.cs
VideoExport.Core/Extensions/MP4Extension.cs
VideoExport.Core/Resources/English.xml
VideoExport.Core/Resources/中文.xml
VideoExport.Core/VideoExport.Core.projitems
VideoExport.Core/VideoExport.cs

Adds a toggle under the MP4 to use GPU-accelerated codecs. It's a large increase in encoding speed at the cost of compression efficiency. In my case 5x faster encoding and 2-3x larger output file (12600KF -> 3060ti).
Adds the MOV extension and Apple ProRes 4444 codec for it.

[VE] Additional MP4 codecs and MOV extension

---

NodesConstraints.Core/NodesConstraints.cs

Fixes an issue where NC does not update when a character isn't in the scene:
https://github.com/user-attachments/assets/45a3053d-5993-4966-a9fd-4e7a0f652796
This happens because the postfix looks ahead in an attempt to find the last LateUpdate call, but `_totalActiveExpressions = 0`:
https://github.com/IllusionMods/HSPlugins/blob/35d1deb454717f78a5a20ba636609fa597e24730/NodesConstraints.Core/NodesConstraints.cs#L686-L695
The reason this is called in the first place is because an `Expression` component is added to the `MainCamera` in `Init()` to address this dependency on a character. This dummy expression is excluded by the Count filter, causing `_totalActiveExpression` to be off by one.

[NC] Fix NC being dependent on a character being in the scene

---

VideoExport.Core/ScreenshotPlugins/Builtin.cs
VideoExport.Core/ScreenshotPlugins/ScreencapPlugin.cs
VideoExport.Core/TextureEncoder.cs
VideoExport.Core/VideoExport.cs

This PR adds JPG encoding to the Builtin screenshot tool and fixes the following issue:
- When ScreenshotManager is set to JPG, VE exports a .png encoded image with a .jpg extension.
Also addresses issue reported in BepisPlugins: https://github.com/IllusionMods/BepisPlugins/issues/214

[VE] Add JPG encoding in ScreenshotManager (KK) and Builtin

---

VideoExport.Core/ScreenshotPlugins/ReshadePlugin.cs
VideoExport.Core/VideoExport.Core.projitems
VideoExport.Core/VideoExport.cs

This PR adds support for Reshade effects in Video Export.
The KKReshade addon writes the post-processed frame to shared memory and the ReshadePlugin picks it up in the following frame.
If the user does not have the KKReshade addon installed, the screenshot plugin will fail to map the shared memory in `Init` and will not be added to VideoExport.
KKReshade: https://github.com/vea-sa/KKReshade

[VE] Add Reshade screenshot plugin

---

VideoExport.Core/ScreenshotPlugins/ReshadePlugin.cs

- Added a toggle for removing the alpha channel. Many effects zero out the alpha channel, causing fully transparent screenshots when encoding as PNG.
- Removed EXR because we currently only have the standard RGBA image format.
- Fixed auto-hide to work as the user expects (auto-hide now means hide, not toggle to the other state).

[VE] Improvements and fixes for the reshade plugin

---

Core.PoseEditor/AMModules/CollidersEditor.cs

I was having a bug with colliders not being added to the colliders list properly when a new character was added to a scene, the colliders were only getting added to the list properly when you opened an existing scene with characters, only those that were already there had the full list. This manually fixes the issue to anybody that requires a refresh.

QoL update Colliders Editor | Force refresh colliders

---

VideoExport.Core/Extensions/AFFMPEGBasedExtension.cs
VideoExport.Core/Extensions/GIFExtension.cs
VideoExport.Core/Extensions/WEBPExtension.cs
VideoExport.Core/Resources/English.xml
VideoExport.Core/Resources/中文.xml
VideoExport.Core/Styles.cs
VideoExport.Core/VideoExport.cs

The `gifski` tool generates per-frame color palettes with mandatory dithering, which causes flickering in Discord. This PR adds an option to generate GIFs with `ffmpeg`. In this case we need to run `ffmpeg` external process twice: first to generate a global color palette, then the image generation itself.
It ended up a bit of a conditional mess because `ffmpeg` palette generation and `gifski` do not have standard output. But I am keeping `gifski` because `ffmpeg` can't do per-frame palettes.
External process standard output is now handled async + a few misc fixes.

[VE] GIF improvements and general fixes

---

VideoExport.Core/VideoExport.cs

Fixes https://github.com/IllusionMods/HSPlugins/issues/150.
I think this issue has been there for a very long time. In fact, almost the entire config is not bound properly using `ConfigEntry<>`.
It exposes many internal values (e.g. indexes) that should stay hidden and not pollute the F1 menu. I'll review the entire config later when I find the time.

[VE] Fix Frames/Output folders not saving from config menu

---

Core.PoseEditor/CharaPoseController.cs

issue:
when i try to exit studio, i meet null reference like below
NullReferenceException
at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
at HSPE.AMModules.BlendShapesEditor.OnDisable () [0x0003b] in <57951205e4844ff1af8e92ebb1481ac1>:0 
at (wrapper delegate-invoke) <Module>.invoke_void()
at HSPE.PoseController.OnDisable () [0x00000] in <57951205e4844ff1af8e92ebb1481ac1>:0
solution:
check null pointer before variable used.

remove null reference during destroy on PoseEditor
